// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hold.sql

package inventorydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHoldById = `-- name: DeleteHoldById :exec
DELETE FROM holds WHERE id = $1
`

func (q *Queries) DeleteHoldById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHoldById, id)
	return err
}

const insertHoldWithFreeSlot = `-- name: InsertHoldWithFreeSlot :one
INSERT INTO holds (id, date, room_type_id, booking_id, slot_no, status, expired_at)
SELECT
    $1,
    $2,
    $3,
    $4,
    s.slot_no,
    'temporary_hold',
    $5
FROM generate_series(
    1,
    (SELECT quantity_available FROM inventories
     WHERE date = $2 AND room_type_id = $3 AND is_closed = false)
) AS s(slot_no)
WHERE NOT EXISTS (
    SELECT 1 FROM holds h
    WHERE h.room_type_id = $3 AND h.date = $2 AND h.slot_no = s.slot_no
)
ORDER BY s.slot_no
LIMIT 1
RETURNING id, room_type_id, date, booking_id, status, expired_at, slot_no, created_at, updated_at
`

type InsertHoldWithFreeSlotParams struct {
	HoldID     uuid.UUID
	Date       time.Time
	RoomTypeID uuid.UUID
	BookingID  uuid.UUID
	ExpiredAt  pgtype.Timestamptz
}

func (q *Queries) InsertHoldWithFreeSlot(ctx context.Context, arg InsertHoldWithFreeSlotParams) (Hold, error) {
	row := q.db.QueryRow(ctx, insertHoldWithFreeSlot,
		arg.HoldID,
		arg.Date,
		arg.RoomTypeID,
		arg.BookingID,
		arg.ExpiredAt,
	)
	var i Hold
	err := row.Scan(
		&i.ID,
		&i.RoomTypeID,
		&i.Date,
		&i.BookingID,
		&i.Status,
		&i.ExpiredAt,
		&i.SlotNo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHoldsByRoomTypeIdAndDate = `-- name: ListHoldsByRoomTypeIdAndDate :many
SELECT id, room_type_id, date, booking_id, status, expired_at, slot_no, created_at, updated_at FROM holds WHERE date = $1 AND room_type_id = $2
`

type ListHoldsByRoomTypeIdAndDateParams struct {
	Date       time.Time
	RoomTypeID uuid.UUID
}

func (q *Queries) ListHoldsByRoomTypeIdAndDate(ctx context.Context, arg ListHoldsByRoomTypeIdAndDateParams) ([]Hold, error) {
	rows, err := q.db.Query(ctx, listHoldsByRoomTypeIdAndDate, arg.Date, arg.RoomTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hold
	for rows.Next() {
		var i Hold
		if err := rows.Scan(
			&i.ID,
			&i.RoomTypeID,
			&i.Date,
			&i.BookingID,
			&i.Status,
			&i.ExpiredAt,
			&i.SlotNo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHold = `-- name: UpsertHold :exec
INSERT INTO holds (
    id, date, room_type_id, booking_id, status, expired_at, slot_no
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    expired_at = EXCLUDED.expired_at,
    updated_at = now()
`

type UpsertHoldParams struct {
	ID         uuid.UUID
	Date       time.Time
	RoomTypeID uuid.UUID
	BookingID  uuid.UUID
	Status     HoldStatus
	ExpiredAt  pgtype.Timestamptz
	SlotNo     int32
}

func (q *Queries) UpsertHold(ctx context.Context, arg UpsertHoldParams) error {
	_, err := q.db.Exec(ctx, upsertHold,
		arg.ID,
		arg.Date,
		arg.RoomTypeID,
		arg.BookingID,
		arg.Status,
		arg.ExpiredAt,
		arg.SlotNo,
	)
	return err
}
