// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: inventory.sql

package inventorydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getInventoriesByDateAndRoomTypeId = `-- name: GetInventoriesByDateAndRoomTypeId :one
SELECT room_type_id, date, fee, quantity_available, is_closed, created_at, updated_at FROM inventories WHERE date = $1 AND room_type_id = $2
`

type GetInventoriesByDateAndRoomTypeIdParams struct {
	Date       time.Time
	RoomTypeID uuid.UUID
}

func (q *Queries) GetInventoriesByDateAndRoomTypeId(ctx context.Context, arg GetInventoriesByDateAndRoomTypeIdParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoriesByDateAndRoomTypeId, arg.Date, arg.RoomTypeID)
	var i Inventory
	err := row.Scan(
		&i.RoomTypeID,
		&i.Date,
		&i.Fee,
		&i.QuantityAvailable,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoriesByRoomTypeId = `-- name: GetInventoriesByRoomTypeId :many
SELECT room_type_id, date, fee, quantity_available, is_closed, created_at, updated_at FROM inventories WHERE room_type_id = $1
`

func (q *Queries) GetInventoriesByRoomTypeId(ctx context.Context, roomTypeID uuid.UUID) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, getInventoriesByRoomTypeId, roomTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.RoomTypeID,
			&i.Date,
			&i.Fee,
			&i.QuantityAvailable,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryByRoomTypeIdAndDateForUpdate = `-- name: GetInventoryByRoomTypeIdAndDateForUpdate :one
SELECT room_type_id, date, fee, quantity_available, is_closed, created_at, updated_at FROM inventories
WHERE room_type_id = $1 AND date = $2
FOR UPDATE
`

type GetInventoryByRoomTypeIdAndDateForUpdateParams struct {
	RoomTypeID uuid.UUID
	Date       time.Time
}

func (q *Queries) GetInventoryByRoomTypeIdAndDateForUpdate(ctx context.Context, arg GetInventoryByRoomTypeIdAndDateForUpdateParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByRoomTypeIdAndDateForUpdate, arg.RoomTypeID, arg.Date)
	var i Inventory
	err := row.Scan(
		&i.RoomTypeID,
		&i.Date,
		&i.Fee,
		&i.QuantityAvailable,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInventory = `-- name: UpsertInventory :exec
INSERT INTO inventories (
    room_type_id, fee, quantity_available, is_closed, date
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (id) DO UPDATE SET
    fee = EXCLUDED.fee,
    quantity_available = EXCLUDED.quantity_available,
    is_closed = EXCLUDED.is_closed,
    updated_at     = now()
`

type UpsertInventoryParams struct {
	RoomTypeID        uuid.UUID
	Fee               int32
	QuantityAvailable int32
	IsClosed          bool
	Date              time.Time
}

func (q *Queries) UpsertInventory(ctx context.Context, arg UpsertInventoryParams) error {
	_, err := q.db.Exec(ctx, upsertInventory,
		arg.RoomTypeID,
		arg.Fee,
		arg.QuantityAvailable,
		arg.IsClosed,
		arg.Date,
	)
	return err
}
