// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booker.sql

package bookerdb

import (
	"context"

	"github.com/google/uuid"
)

const getBooker = `-- name: GetBooker :one
SELECT id, first_name, last_name, postal_code, phone_number, prefecture, city, street_address, building, created_at, updated_at, subject FROM bookers WHERE id = $1
`

func (q *Queries) GetBooker(ctx context.Context, id uuid.UUID) (Booker, error) {
	row := q.db.QueryRow(ctx, getBooker, id)
	var i Booker
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PostalCode,
		&i.PhoneNumber,
		&i.Prefecture,
		&i.City,
		&i.StreetAddress,
		&i.Building,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
	)
	return i, err
}

const getBookerBySubject = `-- name: GetBookerBySubject :one
SELECT id, first_name, last_name, postal_code, phone_number, prefecture, city, street_address, building, created_at, updated_at, subject FROM bookers WHERE subject = $1
`

func (q *Queries) GetBookerBySubject(ctx context.Context, subject *string) (Booker, error) {
	row := q.db.QueryRow(ctx, getBookerBySubject, subject)
	var i Booker
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PostalCode,
		&i.PhoneNumber,
		&i.Prefecture,
		&i.City,
		&i.StreetAddress,
		&i.Building,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
	)
	return i, err
}

const upsertBooker = `-- name: UpsertBooker :exec
INSERT INTO bookers (
    id, first_name, last_name, postal_code, phone_number,
    prefecture, city, street_address, building, subject
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (id) DO UPDATE SET
    first_name     = EXCLUDED.first_name,
    last_name      = EXCLUDED.last_name,
    postal_code    = EXCLUDED.postal_code,
    phone_number   = EXCLUDED.phone_number,
    prefecture     = EXCLUDED.prefecture,
    city           = EXCLUDED.city,
    street_address = EXCLUDED.street_address,
    building       = EXCLUDED.building,
    updated_at     = now()
`

type UpsertBookerParams struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	PostalCode    string
	PhoneNumber   string
	Prefecture    string
	City          string
	StreetAddress string
	Building      string
	Subject       *string
}

func (q *Queries) UpsertBooker(ctx context.Context, arg UpsertBookerParams) error {
	_, err := q.db.Exec(ctx, upsertBooker,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.PostalCode,
		arg.PhoneNumber,
		arg.Prefecture,
		arg.City,
		arg.StreetAddress,
		arg.Building,
		arg.Subject,
	)
	return err
}
