// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package bookerdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Accommodation struct {
	ID            uuid.UUID
	Name          string
	PhoneNumber   string
	PostalCode    string
	Prefecture    string
	City          string
	StreetAddress string
	Building      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Booker struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	PostalCode    string
	PhoneNumber   string
	Prefecture    string
	City          string
	StreetAddress string
	Building      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type RoomType struct {
	ID              uuid.UUID
	AccommodationID uuid.UUID
	Name            string
	Capacity        int32
	HasPrivateBath  bool
	HasBalcony      bool
	DeletedAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
