// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: booking.sql

package bookingdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getBookingById = `-- name: GetBookingById :one
SELECT id, booker_id, room_type_id, total_fee, checkin_date, checkout_date, status, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingById(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingById, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookerID,
		&i.RoomTypeID,
		&i.TotalFee,
		&i.CheckinDate,
		&i.CheckoutDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByIdForUpdate = `-- name: GetBookingByIdForUpdate :one
SELECT id, booker_id, room_type_id, total_fee, checkin_date, checkout_date, status, created_at, updated_at FROM bookings WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetBookingByIdForUpdate(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByIdForUpdate, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.BookerID,
		&i.RoomTypeID,
		&i.TotalFee,
		&i.CheckinDate,
		&i.CheckoutDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByBookerId = `-- name: ListBookingsByBookerId :many
SELECT id, booker_id, room_type_id, total_fee, checkin_date, checkout_date, status, created_at, updated_at FROM bookings
WHERE booker_id = $1
ORDER BY checkin_date DESC
`

func (q *Queries) ListBookingsByBookerId(ctx context.Context, bookerID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByBookerId, bookerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.BookerID,
			&i.RoomTypeID,
			&i.TotalFee,
			&i.CheckinDate,
			&i.CheckoutDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBooking = `-- name: UpsertBooking :exec
INSERT INTO bookings (
    id, booker_id, room_type_id, total_fee, checkin_date, checkout_date, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE SET
    total_fee     = EXCLUDED.total_fee,
    checkin_date  = EXCLUDED.checkin_date,
    checkout_date = EXCLUDED.checkout_date,
    status        = EXCLUDED.status,
    updated_at    = now()
`

type UpsertBookingParams struct {
	ID           uuid.UUID
	BookerID     uuid.UUID
	RoomTypeID   uuid.UUID
	TotalFee     int32
	CheckinDate  time.Time
	CheckoutDate time.Time
	Status       BookingStatus
}

func (q *Queries) UpsertBooking(ctx context.Context, arg UpsertBookingParams) error {
	_, err := q.db.Exec(ctx, upsertBooking,
		arg.ID,
		arg.BookerID,
		arg.RoomTypeID,
		arg.TotalFee,
		arg.CheckinDate,
		arg.CheckoutDate,
		arg.Status,
	)
	return err
}
