// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: guest.sql

package bookingdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteGuestById = `-- name: DeleteGuestById :exec
DELETE FROM guests WHERE id = $1
`

func (q *Queries) DeleteGuestById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuestById, id)
	return err
}

const deleteGuestsByBookingId = `-- name: DeleteGuestsByBookingId :exec
DELETE FROM guests WHERE booking_id = $1
`

func (q *Queries) DeleteGuestsByBookingId(ctx context.Context, bookingID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuestsByBookingId, bookingID)
	return err
}

const listGuestsByBookingId = `-- name: ListGuestsByBookingId :many
SELECT id, booking_id, first_name, last_name, created_at, updated_at FROM guests
WHERE booking_id = $1
ORDER BY created_at
`

func (q *Queries) ListGuestsByBookingId(ctx context.Context, bookingID uuid.UUID) ([]Guest, error) {
	rows, err := q.db.Query(ctx, listGuestsByBookingId, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuest = `-- name: UpsertGuest :exec
INSERT INTO guests (
    id, booking_id, first_name, last_name
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name  = EXCLUDED.last_name,
    updated_at = now()
`

type UpsertGuestParams struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	FirstName string
	LastName  string
}

func (q *Queries) UpsertGuest(ctx context.Context, arg UpsertGuestParams) error {
	_, err := q.db.Exec(ctx, upsertGuest,
		arg.ID,
		arg.BookingID,
		arg.FirstName,
		arg.LastName,
	)
	return err
}
