// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accommodation.sql

package accommodationdb

import (
	"context"

	"github.com/google/uuid"
)

const getAccommodation = `-- name: GetAccommodation :one
SELECT id, name, phone_number, postal_code, prefecture, city, street_address, building, created_at, updated_at FROM accommodations WHERE id = $1
`

func (q *Queries) GetAccommodation(ctx context.Context, id uuid.UUID) (Accommodation, error) {
	row := q.db.QueryRow(ctx, getAccommodation, id)
	var i Accommodation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.PostalCode,
		&i.Prefecture,
		&i.City,
		&i.StreetAddress,
		&i.Building,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccommodation = `-- name: UpsertAccommodation :exec
INSERT INTO accommodations (
    id, name, phone_number, postal_code, prefecture, city, street_address, building
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE SET
    name           = EXCLUDED.name,
    phone_number   = EXCLUDED.phone_number,
    postal_code    = EXCLUDED.postal_code,
    prefecture     = EXCLUDED.prefecture,
    city           = EXCLUDED.city,
    street_address = EXCLUDED.street_address,
    building       = EXCLUDED.building,
    updated_at     = now()
`

type UpsertAccommodationParams struct {
	ID            uuid.UUID
	Name          string
	PhoneNumber   string
	PostalCode    string
	Prefecture    string
	City          string
	StreetAddress string
	Building      string
}

func (q *Queries) UpsertAccommodation(ctx context.Context, arg UpsertAccommodationParams) error {
	_, err := q.db.Exec(ctx, upsertAccommodation,
		arg.ID,
		arg.Name,
		arg.PhoneNumber,
		arg.PostalCode,
		arg.Prefecture,
		arg.City,
		arg.StreetAddress,
		arg.Building,
	)
	return err
}
