// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accommodation.sql

package accommodationdb

import (
	"context"

	"github.com/google/uuid"
)

const getAccommodation = `-- name: GetAccommodation :one
SELECT id, name, phone_number, postal_code, prefecture, city, street_address, building, created_at, updated_at, operator_subject FROM accommodations WHERE id = $1
`

func (q *Queries) GetAccommodation(ctx context.Context, id uuid.UUID) (Accommodation, error) {
	row := q.db.QueryRow(ctx, getAccommodation, id)
	var i Accommodation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.PostalCode,
		&i.Prefecture,
		&i.City,
		&i.StreetAddress,
		&i.Building,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OperatorSubject,
	)
	return i, err
}

const getRoomTypeOperator = `-- name: GetRoomTypeOperator :one
SELECT a.operator_subject
FROM room_types rt
JOIN accommodations a ON a.id = rt.accommodation_id
WHERE rt.id = $1 AND rt.deleted_at IS NULL
`

func (q *Queries) GetRoomTypeOperator(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getRoomTypeOperator, id)
	var operator_subject *string
	err := row.Scan(&operator_subject)
	return operator_subject, err
}

const listAccommodations = `-- name: ListAccommodations :many
SELECT id, name, phone_number, postal_code, prefecture, city, street_address, building, created_at, updated_at, operator_subject FROM accommodations
ORDER BY created_at DESC
`

func (q *Queries) ListAccommodations(ctx context.Context) ([]Accommodation, error) {
	rows, err := q.db.Query(ctx, listAccommodations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accommodation
	for rows.Next() {
		var i Accommodation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.PostalCode,
			&i.Prefecture,
			&i.City,
			&i.StreetAddress,
			&i.Building,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OperatorSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccommodationsByOperator = `-- name: ListAccommodationsByOperator :many
SELECT id, name, phone_number, postal_code, prefecture, city, street_address, building, created_at, updated_at, operator_subject FROM accommodations
WHERE operator_subject = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAccommodationsByOperator(ctx context.Context, operatorSubject *string) ([]Accommodation, error) {
	rows, err := q.db.Query(ctx, listAccommodationsByOperator, operatorSubject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accommodation
	for rows.Next() {
		var i Accommodation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.PostalCode,
			&i.Prefecture,
			&i.City,
			&i.StreetAddress,
			&i.Building,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OperatorSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccommodation = `-- name: UpsertAccommodation :exec
INSERT INTO accommodations (
    id, name, phone_number, postal_code, prefecture, city, street_address, building, operator_subject
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    name           = EXCLUDED.name,
    phone_number   = EXCLUDED.phone_number,
    postal_code    = EXCLUDED.postal_code,
    prefecture     = EXCLUDED.prefecture,
    city           = EXCLUDED.city,
    street_address = EXCLUDED.street_address,
    building       = EXCLUDED.building,
    updated_at     = now()
`

type UpsertAccommodationParams struct {
	ID              uuid.UUID
	Name            string
	PhoneNumber     string
	PostalCode      string
	Prefecture      string
	City            string
	StreetAddress   string
	Building        string
	OperatorSubject *string
}

func (q *Queries) UpsertAccommodation(ctx context.Context, arg UpsertAccommodationParams) error {
	_, err := q.db.Exec(ctx, upsertAccommodation,
		arg.ID,
		arg.Name,
		arg.PhoneNumber,
		arg.PostalCode,
		arg.Prefecture,
		arg.City,
		arg.StreetAddress,
		arg.Building,
		arg.OperatorSubject,
	)
	return err
}
