// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room_type.sql

package accommodationdb

import (
	"context"

	"github.com/google/uuid"
)

const getRoomType = `-- name: GetRoomType :one
SELECT id, accommodation_id, name, capacity, has_private_bath, has_balcony, deleted_at, created_at, updated_at FROM room_types
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRoomType(ctx context.Context, id uuid.UUID) (RoomType, error) {
	row := q.db.QueryRow(ctx, getRoomType, id)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.AccommodationID,
		&i.Name,
		&i.Capacity,
		&i.HasPrivateBath,
		&i.HasBalcony,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoomTypesByAccommodation = `-- name: ListRoomTypesByAccommodation :many
SELECT id, accommodation_id, name, capacity, has_private_bath, has_balcony, deleted_at, created_at, updated_at FROM room_types
WHERE accommodation_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListRoomTypesByAccommodation(ctx context.Context, accommodationID uuid.UUID) ([]RoomType, error) {
	rows, err := q.db.Query(ctx, listRoomTypesByAccommodation, accommodationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomType
	for rows.Next() {
		var i RoomType
		if err := rows.Scan(
			&i.ID,
			&i.AccommodationID,
			&i.Name,
			&i.Capacity,
			&i.HasPrivateBath,
			&i.HasBalcony,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRoomType = `-- name: SoftDeleteRoomType :exec
UPDATE room_types
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRoomType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteRoomType, id)
	return err
}

const upsertRoomType = `-- name: UpsertRoomType :exec
INSERT INTO room_types (
    id, accommodation_id, name, capacity, has_private_bath, has_balcony
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (id) DO UPDATE SET
    name             = EXCLUDED.name,
    capacity         = EXCLUDED.capacity,
    has_private_bath = EXCLUDED.has_private_bath,
    has_balcony      = EXCLUDED.has_balcony,
    updated_at       = now()
`

type UpsertRoomTypeParams struct {
	ID              uuid.UUID
	AccommodationID uuid.UUID
	Name            string
	Capacity        int32
	HasPrivateBath  bool
	HasBalcony      bool
}

func (q *Queries) UpsertRoomType(ctx context.Context, arg UpsertRoomTypeParams) error {
	_, err := q.db.Exec(ctx, upsertRoomType,
		arg.ID,
		arg.AccommodationID,
		arg.Name,
		arg.Capacity,
		arg.HasPrivateBath,
		arg.HasBalcony,
	)
	return err
}
