// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package searchdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchRoomTypes = `-- name: SearchRoomTypes :many
WITH available AS (
    SELECT i.room_type_id, i.date, i.fee
    FROM inventories i
    LEFT JOIN holds h
        ON h.room_type_id = i.room_type_id AND h.date = i.date
    WHERE i.date >= $5
      AND i.date < $6
      AND i.is_closed = false
    GROUP BY i.room_type_id, i.date, i.fee, i.quantity_available
    HAVING i.quantity_available - COUNT(h.id) > 0
)
SELECT
    rt.id            AS room_type_id,
    rt.name          AS room_type_name,
    rt.capacity,
    rt.has_private_bath,
    rt.has_balcony,
    a.id             AS accommodation_id,
    a.name           AS accommodation_name,
    a.prefecture,
    a.city,
    SUM(av.fee)::int AS total_fee
FROM available av
JOIN room_types rt     ON rt.id = av.room_type_id
JOIN accommodations a  ON a.id = rt.accommodation_id
WHERE rt.deleted_at IS NULL
  AND rt.capacity >= $1::int
  AND ($2::text = '' OR a.prefecture = $2::text)
GROUP BY rt.id, rt.name, rt.capacity, rt.has_private_bath, rt.has_balcony,
         a.id, a.name, a.prefecture, a.city
HAVING COUNT(av.date) = $3::int
   AND ($4::int = 0 OR SUM(av.fee) <= $4::int)
ORDER BY SUM(av.fee)
`

type SearchRoomTypesParams struct {
	Guests       int32
	Prefecture   string
	Nights       int32
	MaxFee       int32
	CheckinDate  time.Time
	CheckoutDate time.Time
}

type SearchRoomTypesRow struct {
	RoomTypeID        uuid.UUID
	RoomTypeName      string
	Capacity          int32
	HasPrivateBath    bool
	HasBalcony        bool
	AccommodationID   uuid.UUID
	AccommodationName string
	Prefecture        string
	City              string
	TotalFee          int32
}

func (q *Queries) SearchRoomTypes(ctx context.Context, arg SearchRoomTypesParams) ([]SearchRoomTypesRow, error) {
	rows, err := q.db.Query(ctx, searchRoomTypes,
		arg.Guests,
		arg.Prefecture,
		arg.Nights,
		arg.MaxFee,
		arg.CheckinDate,
		arg.CheckoutDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRoomTypesRow
	for rows.Next() {
		var i SearchRoomTypesRow
		if err := rows.Scan(
			&i.RoomTypeID,
			&i.RoomTypeName,
			&i.Capacity,
			&i.HasPrivateBath,
			&i.HasBalcony,
			&i.AccommodationID,
			&i.AccommodationName,
			&i.Prefecture,
			&i.City,
			&i.TotalFee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
