// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package bookingdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BookingStatus string

const (
	BookingStatusTemporaryHold     BookingStatus = "temporary_hold"
	BookingStatusProcessingPayment BookingStatus = "processing_payment"
	BookingStatusCancelled         BookingStatus = "cancelled"
	BookingStatusConfirmed         BookingStatus = "confirmed"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus
	Valid         bool // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type HoldStatus string

const (
	HoldStatusTemporaryHold     HoldStatus = "temporary_hold"
	HoldStatusProcessingPayment HoldStatus = "processing_payment"
	HoldStatusConfirmed         HoldStatus = "confirmed"
)

func (e *HoldStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HoldStatus(s)
	case string:
		*e = HoldStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HoldStatus: %T", src)
	}
	return nil
}

type NullHoldStatus struct {
	HoldStatus HoldStatus
	Valid      bool // Valid is true if HoldStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHoldStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HoldStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HoldStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHoldStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HoldStatus), nil
}

type Accommodation struct {
	ID            uuid.UUID
	Name          string
	PhoneNumber   string
	PostalCode    string
	Prefecture    string
	City          string
	StreetAddress string
	Building      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Booker struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	PostalCode    string
	PhoneNumber   string
	Prefecture    string
	City          string
	StreetAddress string
	Building      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Booking struct {
	ID           uuid.UUID
	BookerID     uuid.UUID
	RoomTypeID   uuid.UUID
	TotalFee     int32
	CheckinDate  time.Time
	CheckoutDate time.Time
	Status       BookingStatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Guest struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Hold struct {
	ID         uuid.UUID
	RoomTypeID uuid.UUID
	Date       time.Time
	BookingID  uuid.UUID
	Status     HoldStatus
	ExpiredAt  pgtype.Timestamptz
	SlotNo     int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Inventory struct {
	RoomTypeID        uuid.UUID
	Date              time.Time
	Fee               int32
	QuantityAvailable int32
	IsClosed          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type RoomType struct {
	ID              uuid.UUID
	AccommodationID uuid.UUID
	Name            string
	Capacity        int32
	HasPrivateBath  bool
	HasBalcony      bool
	DeletedAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
