// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: inventory.sql

package inventorydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getInventoriesById = `-- name: GetInventoriesById :one
SELECT id, room_type_id, date, fee, quantity_available, is_closed, created_at, updated_at FROM inventories WHERE id = $1
`

func (q *Queries) GetInventoriesById(ctx context.Context, id uuid.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoriesById, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.RoomTypeID,
		&i.Date,
		&i.Fee,
		&i.QuantityAvailable,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoriesByRoomTypeId = `-- name: GetInventoriesByRoomTypeId :many
SELECT id, room_type_id, date, fee, quantity_available, is_closed, created_at, updated_at FROM inventories WHERE room_type_id = $1
`

func (q *Queries) GetInventoriesByRoomTypeId(ctx context.Context, roomTypeID uuid.UUID) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, getInventoriesByRoomTypeId, roomTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.RoomTypeID,
			&i.Date,
			&i.Fee,
			&i.QuantityAvailable,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryByRoomTypeIdAndDateForUpdate = `-- name: GetInventoryByRoomTypeIdAndDateForUpdate :one
SELECT id, room_type_id, date, fee, quantity_available, is_closed, created_at, updated_at FROM inventories
WHERE room_type_id = $1 AND date = $2
FOR UPDATE
`

type GetInventoryByRoomTypeIdAndDateForUpdateParams struct {
	RoomTypeID uuid.UUID
	Date       time.Time
}

func (q *Queries) GetInventoryByRoomTypeIdAndDateForUpdate(ctx context.Context, arg GetInventoryByRoomTypeIdAndDateForUpdateParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByRoomTypeIdAndDateForUpdate, arg.RoomTypeID, arg.Date)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.RoomTypeID,
		&i.Date,
		&i.Fee,
		&i.QuantityAvailable,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHoldsByInventoryId = `-- name: ListHoldsByInventoryId :many
SELECT id, inventory_id, booking_id, status, expired_at, slot_no, created_at, updated_at FROM holds WHERE inventory_id = $1 ORDER BY slot_no
`

func (q *Queries) ListHoldsByInventoryId(ctx context.Context, inventoryID uuid.UUID) ([]Hold, error) {
	rows, err := q.db.Query(ctx, listHoldsByInventoryId, inventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hold
	for rows.Next() {
		var i Hold
		if err := rows.Scan(
			&i.ID,
			&i.InventoryID,
			&i.BookingID,
			&i.Status,
			&i.ExpiredAt,
			&i.SlotNo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openInventoryByRoomTypeIdAndDate = `-- name: OpenInventoryByRoomTypeIdAndDate :exec
UPDATE inventories SET is_closed = false WHERE room_type_id = $1 AND date = $2
`

type OpenInventoryByRoomTypeIdAndDateParams struct {
	RoomTypeID uuid.UUID
	Date       time.Time
}

func (q *Queries) OpenInventoryByRoomTypeIdAndDate(ctx context.Context, arg OpenInventoryByRoomTypeIdAndDateParams) error {
	_, err := q.db.Exec(ctx, openInventoryByRoomTypeIdAndDate, arg.RoomTypeID, arg.Date)
	return err
}

const upsertInventory = `-- name: UpsertInventory :exec
INSERT INTO inventories (
    id, room_type_id, fee, quantity_available, is_closed, date
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (id) DO UPDATE SET
    fee = EXCLUDED.fee,
    quantity_available = EXCLUDED.quantity_available,
    is_closed = EXCLUDED.is_closed,
    updated_at     = now()
`

type UpsertInventoryParams struct {
	ID                uuid.UUID
	RoomTypeID        uuid.UUID
	Fee               int32
	QuantityAvailable int32
	IsClosed          bool
	Date              time.Time
}

func (q *Queries) UpsertInventory(ctx context.Context, arg UpsertInventoryParams) error {
	_, err := q.db.Exec(ctx, upsertInventory,
		arg.ID,
		arg.RoomTypeID,
		arg.Fee,
		arg.QuantityAvailable,
		arg.IsClosed,
		arg.Date,
	)
	return err
}
